#!/bin/bash
set -e
echo "package generic_tlds" > generic_tlds.go
echo "// Code generated by \"update_generic_tlds.sh\"; DO NOT EDIT." >> generic_tlds.go
echo >> generic_tlds.go
curl -s https://data.iana.org/TLD/tlds-alpha-by-domain.txt | grep -v '#' | grep -v '^$' | awk 'BEGIN {print "var GenericTLDs = map[string]bool{"} {print "\""tolower($1)"\":true,"} END{print "}"}' >> generic_tlds.go
gofmt -w generic_tlds.go

